# Generated by Django 4.2.6 on 2023-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1999-05-26"),
            preserve_default=False,
        ),
    ]
